languageCode = "en-us"
title = "DA Holland's Writings"
baseurl = "http://blog.daholland.com"
theme = "darksimplicity"
canonifyurls = true
publishDir = "_public"

[params]
description = "its all bullshit, really"
copyright = "&copy Copyright 2017. DA Holland. Built with Hugo."
google_analytics_id="UA-90008708-1"

[menu]
  [[menu.top]]
  name = "Twitter"
  pre = ""
  weight = -100
  url = "http://www.twitter.com/holland_da"
  [[menu.top]]
  name = "Github"
  pre = ""
  weight = -100
  url = "http://www.github.com/daholland"
